- README.md
> Added Financial Firms

- README.md
> Added Cisco

- README.md
> Added four jobs

- README.md
> Added HRT roles

- README.md
> added amazon and oculus(facebook)

- README.md
> Added dropbox, removed example, fixed capital one spelling

- README.md
- [ x] The proposed changes are in alphabetical order
> Added Nutanix new grad position to list

- README.md
> NASA & Thumbtack

- README.md
> figma new grad

- README.md
> Added Wish

- README.md
> Added Gusto

- README.md
> Adding Palantir

- README.md
Would like to add Two Sigma! In the application, one of the questions asks if you're applying for the new grad role.
> Add Two Sigma

- README.md
> Add Qualtrics

- README.md
https://knowyourmeme.com/memes/profit
> Fix profit meme format

- README.md
> fixed broken link for gusto (denver)

- README.md
> Add Databricks and Flexport

- README.md
> Add Bloomberg

- README.md
> Google and discover

- README.md
Added Quora and Willowtree new grad positions
> Added Quora and Willowtree

- README.md
> Added google and retailmenot

- README.md
> Added Quantcast

- README.md
> Added Airbnb and Lyft

- README.md
> Added Samsara new grad positions

- README.md
> Added Atlassian new grad positions

- README.md
> Add Teachable and Yext positions

- README.md
> Added Factual based in Los Angeles, CA

- README.md
> WillowTree was duplicated, merged into one cell

- README.md
> Adding Visa

- README.md
Link was dead and job is no longer posted on their website
> Removed Essential Products

- README.md
> Added Twilio

- README.md
> Added Sumo Logic

- README.md
> Remove Two Sigma (not new grad)

- README.md
> Update Qualtrics Link

- README.md
> Add Cruise

- README.md
Added
- C3.ai
- Cockroach Labs
- Mongo
- Pure Storage
- Rubrik
> Adding several new companies

- README.md
> Add viasat inc

- README.md
> Add SquareSpace (NY)

- README.md
> Add Oscar Open Positions

- README.md
> Peak6  New Grad position

- README.md
> removed Apple

- README.md
> Adding BlackRock Software Engineering position

- README.md
> Add MemSQL

- README.md
- Fix a typo found on company name
> Fix company name  typo

- README.md
> Quora position is no longer open

- README.md
> Added Asana

- README.md
> Added Expedia

- README.md
Added positions since the original links are getting quite a lot of applications while others are not
> Update Virtu Links

- README.md
> Added TripActions

- README.md
Adds links to [Clutter](https://www.clutter.com) and [Wealthfront](https://www.wealthfront.com)'s new grad applications
> Add new grad applications for Clutter and Wealthfront

- README.md
- [yes ] The proposed changes are in alphabetical order
> Added Oracle SWE new grad

- README.md
> Added General Motors & Paypal

- README.md
✅ The proposed changes are in alphabetical order
> update README with VMware new grad roles

- README.md
Adding www.spatial.is the augmented collaboration company
> Adding Spatial

- README.md
> Added Benchling new grad posting

- README.md
ref: https://github.com/cmackenzie1/new-grads-2020/issues/97
> Fixed Applied Intuition’s link
